### PR TITLE
fix: PR deploy preview

### PR DESCRIPTION
**Pull request by TharinduX**

### CODE REVIEW

**Comment by TharinduX** [comment]
This pull request is being automatically deployed to Netlify.

✅ Preview:

**Comment by nibmcslk** [comment]
This pull request is being automatically deployed to Netlify.

✅ Preview:

**Comment by nibmcslk** [comment]
This pull request is being automatically deployed to Netlify.

✅ Preview:

**Comment by nibmcslk** [comment]
This pull request is being automatically deployed to Netlify.

✅ Preview:

**Comment by nibmcslk** [comment]
This pull request is being automatically deployed to Netlify.

✅ Preview:

**Comment by nibmcslk** [comment]
This pull request is being automatically deployed to Netlify.

✅ Preview:

**Comment by TharinduX** [comment]
Possible bug on preview URL

**Comment by nibmcslk** [comment]
🎉 Published on https://preview.nibmcs.org as production
🚀 Deployed on https://6519de4b58a2270a05a472a9--stirring-maamoul-21e9ba.netlify.app

**Pull request merged**
